[package]
name = "adnix"
version = "0.4.2"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
description = "Rust binary to generate DNSMasq and Unbound configurations from UNIX host files"
license = "MIT"
homepage = "https://github.com/msfjarvis/adnix-rs"
repository = "https://github.com/msfjarvis/adnix-rs"
readme = "README.md"
include = ["src/**/*", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = [ "color", "deprecated", "derive" ] }
color-eyre = { version = "0.6.2", default-features = false }
regex = "1.6.0"
ureq = "2.5.0"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
