[package]
name = "adnix"
version = "0.4.1-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Rust binary to generate DNSMasq and Unbound configurations from UNIX host files"
license = "MIT"
homepage = "https://github.com/msfjarvis/adnix-rs"
repository = "https://github.com/msfjarvis/adnix-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.1", features = ["yaml", "wrap_help"] }
regex = "1.3.9"
ureq = "1.1.1"

[build-dependencies]
clap = { version = "2.33.1", features = ["yaml"] }
