[package]
name = "adnix"
version = "0.4.2-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Rust binary to generate DNSMasq and Unbound configurations from UNIX host files"
license = "MIT"
homepage = "https://github.com/msfjarvis/adnix-rs"
repository = "https://github.com/msfjarvis/adnix-rs"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3", features = ["yaml", "wrap_help"] }
color-eyre = { version = "0.5.10", default-features = false }
regex = "1.4.4"
ureq = "2.0.2"

[build-dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
